"""
BVR Research Worker — Researches topics and produces decision-ready summaries.
"""

import asyncio
import json
from typing import Dict, Any
from workers.base import BaseWorker
from bvr_sdk import (
    EventEnvelope, emit_event, trace_span,
    ai_gateway_call, upload_artifact
)

class ResearchWorker(BaseWorker):
    worker_id = "topic-synthesizer"
    capabilities = ["research.topic", "summarize", "synthesize"]
    version = "2.0.0"

    @trace_span("research.synthesize")
    async def handle(self, event: EventEnvelope) -> Dict[str, Any]:
        topic = event.payload["topic"]
        depth = event.payload.get("depth", "standard")

        print(f"[RESEARCH] Researching: {topic} (depth: {depth})")

        # Step 1: Query knowledge base via Capability Matcher
        from bvr_sdk import get_matcher
        matcher = get_matcher()

        # Resolve "knowledge_retrieval" capability
        kb_provider = matcher.resolve("knowledge_retrieval", workflow_id="bvr.research.topic")
        kb_config = matcher.get_provider_config(kb_provider.id)

        # In production: execute knowledge retrieval via plugin
        context = ""  # Placeholder until KB plugin is implemented

        # Step 2: Synthesize with LLM
        prompt = f"""
        Research the following topic and produce a decision-ready summary:

        Topic: {topic}
        Depth: {depth}

        Context from knowledge base:
        {context}

        Requirements:
        - Provide key findings with evidence
        - List trade-offs clearly
        - Give a specific recommendation
        - Include confidence level (High/Medium/Low)
        - Keep it under 500 words for quick decision-making

        Format:
        ## Key Findings
        ## Trade-offs
        ## Recommendation
        ## Confidence: X%
        """

        result = await ai_gateway_call(
            capability="summarization",
            prompt=prompt,
            model_preference="kimi"  # Kimi is good at long-context summarization
        )

        summary = result["text"]

        # Step 3: Generate artifact
        artifact = f"""# Research Summary: {topic}

**Depth:** {depth}  
**Execution ID:** {event.correlation_id}

{summary}

---
*Generated by BVR Research Worker*  
*Model: {result.get("model_used", "unknown")}*  
*Cost: ${result.get("cost_usd", 0):.4f}*
"""

        artifact_url = await upload_artifact(
            data=artifact.encode(),
            path=f"research/{event.correlation_id}/summary.md",
            content_type="text/markdown"
        )

        return {
            "summary": summary,
            "artifact_url": artifact_url,
            "confidence": self._extract_confidence(summary),
            "model_used": result.get("model_used"),
            "cost_usd": result.get("cost_usd"),
            "status": "completed"
        }

    def _extract_confidence(self, text: str) -> str:
        import re
        match = re.search(r'Confidence[:\s]+(\d+)%', text, re.IGNORECASE)
        if match:
            return f"{match.group(1)}%"
        return "Unknown"

if __name__ == "__main__":
    worker = ResearchWorker()
    asyncio.run(worker.start())
